import type { CrosswordPuzzle } from "./types";

// Grid (true = black square):
// Row 0: S T A M P
// Row 1: W   R   R
// Row 2: O B E S E
// Row 3: R   A   S
// Row 4: D I S C S
//
// 1-Across = STAMP, 4-Across = OBESE, 5-Across = DISCS
// 1-Down = SWORD, 2-Down = AREAS, 3-Down = PRESS

export const PUZZLE: CrosswordPuzzle = {
  grid: [
    [true, false, true, true, false, true],
    [false, false, true, false, false, false],
    [false, false, false, true, false, false],
    [true, false, false, false, true, false],
    [false, true, false, false, true, false],
    [false, false, true, false, false, false],
    [false, true, true, false, false, false],
    [true, true, false, false, false, true],
  ],
  clues: [
    {
      number: 1,
      direction: "across",
      clue: "+/- TV-remote button, abbr. ",
      answer: "CH",
      row: 1,
      col: 0,
      length: 2,
    },
    {
      number: 2,
      direction: "across",
      clue: "___ as a fox.",
      answer: "SLY",
      row: 1,
      col: 3,
      length: 3,
    },
    {
      number: 3,
      direction: "across",
      clue: "Top secret US org.",
      answer: "CIA",
      row: 2,
      col: 0,
      length: 3,
    },
    {
      number: 4,
      direction: "across",
      clue: "When doubled, slang for cops.",
      answer: "PO",
      row: 2,
      col: 4,
      length: 2,
    },
    {
      number: 5,
      direction: "across",
      clue: "Swiss peak.",
      answer: "ALP",
      row: 3,
      col: 1,
      length: 3,
    },
    {
      number: 6,
      direction: "across",
      clue: "Warm wavelength of light, abbr.",
      answer: "IR",
      row: 4,
      col: 2,
      length: 2,
    },
    {
      number: 7,
      direction: "across",
      clue: "British unit of weight (abbr.)",
      answer: "LB",
      row: 5,
      col: 0,
      length: 2,
    },
    {
      number: 8,
      direction: "across",
      clue: "Married Ms.",
      answer: "MRS",
      row: 6,
      col: 3,
      length: 3,
    },
    {
      number: 9,
      direction: "across",
      clue: "Second < Minute < Hour < ___.",
      answer: "DAY",
      row: 7,
      col: 2,
      length: 3,
    },
    {
      number: 10,
      direction: "down",
      clue: "___ seeds, or ___ pudding",
      answer: "CHIA",
      row: 0,
      col: 1,
      length: 4,
    },
    {
      number: 11,
      direction: "down",
      clue: "German peak.",
      answer: "ALP",
      row: 0,
      col: 4,
      length: 3,
    },
    {
      number: 12,
      direction: "down",
      clue: "Loop in.",
      answer: "CC",
      row: 1,
      col: 0,
      length: 2,
    },
    {
      number: 13,
      direction: "down",
      clue: "Kids...",
      answer: "YOUTHS",
      row: 1,
      col: 5,
      length: 6,
    },
    {
      number: 14,
      direction: "down",
      clue: '"___ kaffe", or a male Arabic name.',
      answer: "ALI",
      row: 2,
      col: 2,
      length: 3,
    },
    {
      number: 15,
      direction: "down",
      clue: '"Toll!"',
      answer: "PRIMA",
      row: 3,
      col: 3,
      length: 5,
    },
    {
      number: 16,
      direction: "down",
      clue: "I'm ___ (not feeling well)",
      answer: "ILL",
      row: 4,
      col: 0,
      length: 3,
    },
    {
      number: 17,
      direction: "down",
      clue: "You'll never know if you don't ___.",
      answer: "TRY",
      row: 5,
      col: 4,
      length: 3,
    },
  ],
  animationTiles: [
    { row: 1, col: 1 },
    { row: 2, col: 2 },
    { row: 3, col: 3 },
    { row: 2, col: 4 },
    { row: 1, col: 5 },
    { row: 5, col: 1 },
    { row: 4, col: 2 },
    { row: 4, col: 3 },
    { row: 5, col: 4 },
    { row: 5, col: 5 },
    { row: 7, col: 2 },
    { row: 7, col: 3 },
    { row: 7, col: 4 },
  ],
};
